# Pod Deployment

# To deploy to Kubernetes, run: 
# kubectl apply -f culture-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: culture
  namespace: culture
spec:
  replicas: 2
  selector:
    matchLabels:
      app: culture
  template:
    metadata:
      labels:
        app: culture
    spec:
      containers:
        - name: treesbark
          image: culture:simple
          imagePullPolicy: Always
          ports:
          - containerPort: 8089
            name: web
            protocol: HTTP
          readinessProbe:
            httpGet:
              port: web
              path: /