# Pod Port Target

# To deploy to Kubernetes, run: 
# kubectl apply -f culture-nodeport.yaml

apiVersion: v1
kind: Service
metadata:
  name: culture-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: culture
  ports:
    - name: web
      port: 8089
      targetPort: web
      nodePort: 31111